application: helloworld
#application: fa5ce85a4bc0193dde28e7147142c6
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /images
  static_dir: gpxviewer-read-only/examples/gpxviewer/images

- url: /gpxviewer-read-only
  static_dir: gpxviewer-read-only

- url: /(.*\.(xml))
  static_files: gpxviewer-read-only/examples/gpxviewer/\1
  upload: gpxviewer-read-only/examples/gpxviewer/(.*\.(xml))

- url: /(.*\.(html))
  static_files: gpxviewer-read-only/examples/gpxviewer/\1
  upload: gpxviewer-read-only/examples/gpxviewer/(.*\.(html))

- url: /pic
  static_dir: pic

- url: /gpx
  static_files: templates/gpx.html
  upload: templates

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /maplayer/.*
  script: gps.app

- url: /gpxtrack/.*
  script: gps.app

####
- url: /track/pic
  static_dir: pic

- url: /track/css
  static_dir: css

- url: /track/js
  static_dir: js

- url: /track/.*
  script: upload.app
####

- url: /details/[^/]+?show=true|false
  script: upload.app

- url: /details/.*
  script: upload.app

- url: /download/.*
  script: upload.app

- url: /delete/.*
  script: upload.app

- url: /servefile/.*
  script: upload.app

- url: /.*
  script: upload.app

