application: helloworld
#application: fa5ce85a4bc0193dde28e7147142c6
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /js
  static_dir: js

- url: /maplayer/.*
  script: gps.app

- url: /gpxtrack/.*
  script: gps.app

- url: /details/.*
  script: upload.app

- url: /download/.*
  script: upload.app

- url: /delete/.*
  script: upload.app

- url: /servefile/.*
  script: upload.app

- url: /.*
  script: upload.app

