application: helloworld
#application: fa5ce85a4bc0193dde28e7147142c6
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /data
  static_dir: data

- url: /js
  static_dir: js

- url: /gps
  script: gps.app

- url: /track
  script: gps.app

- url: /.*
  script: upload.app
  #script: gps.app

